# -*- coding: utf-8 -*-
"""keras_pneumonia_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YyBNTLAZ6f59hfZR8TzRM7Nh0vkVsdaU
"""

!pip install flask-ngrok

!pip install pyngrok==4.1.1

!ngrok authtoken '2JshTCep75SLaBYg4ghTbFcqcvZ_2L8BNU5PgYC3uBMe6YJ5e'

import flask
from flask import Flask, render_template, request
from flask_ngrok import run_with_ngrok
import os

from keras.models import load_model 
from keras.preprocessing import image
import numpy as np

app = Flask(__name__)
run_with_ngrok(app)
image_folder = os.path.join('chest_xray', 'images')
app.config['UPLOAD_FOLDER'] = image_folder

model = load_model('/content/drive/MyDrive/chest_xray/pneumonia_classification.h5')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/

@app.route('/', methods=['GET'])
def home():
  return render_template('index.html')

@app.route('/', methods=['POST'])
def predict():
  imagefile = request.files['imagefile']
  image_path = './chest_xray/images' + imagefile.filename
  imagefile.save(image_path)

  img = image.load_img(image_path, target_size=(250,250))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)

  images = np.vstack([x])
  classes = model.predict(images, batch_size=10)

  pict = os.path.join(app.config['UPLOAD_FOLDER'], imagefile.filename)

  return render_template('index.html', user_image=pict, prediction_text = 'Patient has Pneumonia: {}'.format(classes[0]))

if __name__ == '__main__':
  app.debug = True
  app.run()